AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
