version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; RAILS_ENV=development bundle exec rails s -b 0.0.0.0" ]
    volumes:
      - .:/todo
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=todo_app"
      - "POSTGRES_PASSWORD=password1234"
    volumes:
      - datavol:/var/lib/postgresql/data
volumes:
  bundle:
  datavol:
